//! Stormglass constants and UI state types.

use crate::challenges::menu::ChallengeType;

// ── Earning rates by rarity ────────────────────────────────────────────
pub const SALVAGE_COMMON: u64 = 1;
pub const SALVAGE_MAGIC: u64 = 1;
pub const SALVAGE_RARE: u64 = 3;
pub const SALVAGE_EPIC: u64 = 8;
pub const SALVAGE_LEGENDARY: u64 = 25;

// ── Challenge win rewards by difficulty ────────────────────────────────
pub const CHALLENGE_NOVICE: u64 = 5;
pub const CHALLENGE_APPRENTICE: u64 = 15;
pub const CHALLENGE_JOURNEYMAN: u64 = 30;
pub const CHALLENGE_MASTER: u64 = 75;

// ── Dungeon treasure cache by size ────────────────────────────────────
pub const DUNGEON_CACHE_SMALL: u64 = 5;
pub const DUNGEON_CACHE_MEDIUM: u64 = 15;
pub const DUNGEON_CACHE_LARGE: u64 = 30;
pub const DUNGEON_CACHE_EPIC: u64 = 50;
pub const DUNGEON_CACHE_LEGENDARY: u64 = 75;

// ── Soulforge failure consolation by target level (index = target - 1) ─
// Levels 1-4 give 0 (100% success rate), levels 5-10 give consolation
pub const SOULFORGE_CONSOLATION: [u64; 10] = [0, 0, 0, 0, 5, 10, 15, 25, 40, 75];

// ── Spending ───────────────────────────────────────────────────────────
pub const INVOKE_TRIAL_COST: u64 = 250;

// ── Chrono Surge ─────────────────────────────────────────────────────
/// (ticks, stormglass_cost, display_label)
pub const CHRONO_SURGE_OPTIONS: [(u64, u64, &str); 4] = [
    (9_000, 500, "15 minutes"),
    (36_000, 2_000, "1 hour"),
    (144_000, 8_000, "4 hours"),
    (288_000, 16_000, "8 hours"),
];

/// Target animation duration for all surge options (in seconds).
/// The batch size is computed so the animation always lasts this long.
pub const CHRONO_SURGE_ANIMATION_SECONDS: u64 = 10;

// ── Exchange UI state ──────────────────────────────────────────────────

/// Phase of the Stormglass Exchange overlay.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExchangePhase {
    Menu,
    InvokeTrial,
    ChronoSurge,
}

/// A single trial option generated by Invoke Trial.
#[derive(Debug, Clone)]
pub struct TrialOption {
    pub challenge_type: ChallengeType,
    pub display_name: String,
}

/// UI state for the Stormglass Exchange overlay.
#[derive(Debug, Clone)]
pub struct ExchangeUiState {
    pub open: bool,
    pub selected_item: usize,
    pub phase: ExchangePhase,
    pub trial_options: Vec<TrialOption>,
    pub trial_selected: usize,
    pub surge_selected: usize,
}

impl ExchangeUiState {
    pub fn new() -> Self {
        Self {
            open: false,
            selected_item: 0,
            phase: ExchangePhase::Menu,
            trial_options: Vec::new(),
            trial_selected: 0,
            surge_selected: 0,
        }
    }

    pub fn open(&mut self) {
        self.open = true;
        self.selected_item = 0;
        self.phase = ExchangePhase::Menu;
        self.trial_options.clear();
        self.trial_selected = 0;
        self.surge_selected = 0;
    }

    pub fn close(&mut self) {
        self.open = false;
        self.phase = ExchangePhase::Menu;
        self.trial_options.clear();
        self.trial_selected = 0;
        self.surge_selected = 0;
    }
}

impl Default for ExchangeUiState {
    fn default() -> Self {
        Self::new()
    }
}

/// Number of menu items in the Exchange (Invoke Trial, Chrono Surge).
pub const EXCHANGE_MENU_ITEMS: usize = 2;

/// Tracks an active Chrono Surge in progress.
pub struct ChronoSurgeState {
    pub ticks_remaining: u64,
    pub ticks_total: u64,
    /// Ticks per 100ms frame — computed so animation lasts CHRONO_SURGE_ANIMATION_SECONDS.
    pub batch_size: u64,
    pub kills: u64,
    pub levels_gained: u32,
    pub items_equipped: u32,
}

impl ChronoSurgeState {
    pub fn new(ticks: u64) -> Self {
        // 10 frames per second * animation seconds = total animation frames
        let animation_frames = CHRONO_SURGE_ANIMATION_SECONDS * 10;
        let batch_size = (ticks / animation_frames).max(1);
        Self {
            ticks_remaining: ticks,
            ticks_total: ticks,
            batch_size,
            kills: 0,
            levels_gained: 0,
            items_equipped: 0,
        }
    }

    /// Progress as a fraction 0.0..=1.0.
    pub fn progress(&self) -> f64 {
        if self.ticks_total == 0 {
            return 1.0;
        }
        (self.ticks_total - self.ticks_remaining) as f64 / self.ticks_total as f64
    }
}

/// Summary shown after a surge completes.
#[allow(dead_code)]
pub struct ChronoSurgeSummary {
    pub kills: u64,
    pub levels_gained: u32,
    pub items_equipped: u32,
    pub ticks_completed: u64,
    pub ticks_total: u64,
}
