//! Shared throbber/spinner utilities for UI animations.

use std::time::{SystemTime, UNIX_EPOCH};

/// Braille spinner characters for animated loading indicators.
const SPINNER: [char; 10] = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
/// Block spinner characters for high-contrast loading indicators.
const BLOCK_SPINNER: [char; 8] = ['▖', '▘', '▝', '▗', '▖', '▘', '▝', '▗'];

/// Atmospheric messages shown while waiting for enemies.
const WAITING_MESSAGES: [&str; 100] = [
    "Scanning the horizon...",
    "Something stirs...",
    "Danger lurks nearby...",
    "The hunt continues...",
    "A foe approaches...",
    "Sensing hostiles...",
    "Shadows gather...",
    "The air grows cold...",
    "Footsteps echo...",
    "Steel at the ready...",
    "Eyes in the dark...",
    "Battle draws near...",
    "Vigilance rewarded...",
    "Prey becomes hunter...",
    "Fortune favors the bold...",
    "Destiny awaits...",
    "The wilds stir...",
    "Trouble brewing...",
    "On guard...",
    "Adventure beckons...",
    "The ground trembles...",
    "A shadow flickers...",
    "Blades thirst for blood...",
    "The wind carries a warning...",
    "Something watches...",
    "An uneasy silence falls...",
    "The darkness deepens...",
    "Instincts sharpen...",
    "A distant roar...",
    "The path narrows...",
    "Dust rises ahead...",
    "Tension fills the air...",
    "A growl in the distance...",
    "Stay alert...",
    "War drums echo...",
    "The calm before the storm...",
    "Bones crunch underfoot...",
    "Something lurks ahead...",
    "The earth holds its breath...",
    "Keeping watch...",
    "A chill runs down your spine...",
    "Torchlight wavers...",
    "The shadows lengthen...",
    "Gripping your weapon tighter...",
    "An omen in the sky...",
    "The silence is deafening...",
    "Leaves rustle unnaturally...",
    "Standing your ground...",
    "The trail grows fresh...",
    "A presence draws near...",
    "Weathering the unknown...",
    "Heart pounding...",
    "The forest whispers...",
    "Nowhere to hide...",
    "Bracing for impact...",
    "Every nerve alive...",
    "Death stalks these lands...",
    "The beast awakens...",
    "No turning back...",
    "Fate closes in...",
    "The wind dies...",
    "Embers glow in the dark...",
    "A howl pierces the night...",
    "The ground shifts beneath you...",
    "Echoes of past battles...",
    "Something breathes nearby...",
    "The fog rolls in...",
    "Readying your stance...",
    "Claws scrape stone...",
    "The smell of blood...",
    "Movement in the brush...",
    "Ancient evil stirs...",
    "The trail of destruction...",
    "A rumble below...",
    "Tightening your grip...",
    "Sparks in the darkness...",
    "The hunt is on...",
    "Ruins whisper warnings...",
    "Chains rattle somewhere...",
    "The earth groans...",
    "Circling the perimeter...",
    "A flicker of movement...",
    "Senses heightened...",
    "The enemy draws close...",
    "Thunder in the distance...",
    "Marking your target...",
    "The shadows dance...",
    "Dread fills the air...",
    "Stalking through silence...",
    "A trap lies ahead...",
    "The moon hides its face...",
    "Predators circle...",
    "Scent of ash and iron...",
    "The world holds still...",
    "Talons click on stone...",
    "Reading the signs...",
    "A war cry rises...",
    "The void stares back...",
    "Blood and glory await...",
    "The final test approaches...",
];

/// Returns the current time in milliseconds since UNIX epoch.
fn current_millis() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
}

/// Returns the current spinner character based on system time.
/// The spinner cycles every 100ms, completing a full rotation every second.
pub fn spinner_char() -> char {
    let millis = current_millis();
    SPINNER[((millis / 100) % 10) as usize]
}

/// Returns a block-based spinner character based on system time.
pub fn block_spinner_char() -> char {
    let millis = current_millis();
    BLOCK_SPINNER[((millis / 100) % BLOCK_SPINNER.len() as u128) as usize]
}

/// Returns a waiting message based on a seed value.
/// The message stays stable for the same seed, changing only when the seed changes.
pub fn waiting_message(seed: u64) -> &'static str {
    WAITING_MESSAGES[(seed.wrapping_mul(7) as usize) % WAITING_MESSAGES.len()]
}

/// Atmospheric messages shown while regenerating HP after a kill.
const REGEN_MESSAGES: [&str; 100] = [
    "Catching your breath...",
    "Wounds knitting shut...",
    "Rest a moment...",
    "Recovering strength...",
    "Bandaging wounds...",
    "Steadying your grip...",
    "The pain subsides...",
    "Vitality returns...",
    "Second wind...",
    "Steeling yourself...",
    "Tending to injuries...",
    "Gathering focus...",
    "A brief respite...",
    "Healing energies flow...",
    "Shaking it off...",
    "Ready soon...",
    "Mending the damage...",
    "Taking a breather...",
    "Fortitude restored...",
    "Regaining composure...",
    "Blood flow steadies...",
    "The ache fades...",
    "Drawing on inner strength...",
    "Scars forming...",
    "Muscles loosen...",
    "Breathing deepens...",
    "The world comes back into focus...",
    "Stretching sore limbs...",
    "A surge of warmth...",
    "Feeling whole again...",
    "The worst has passed...",
    "Adrenaline wearing off...",
    "Flexing tired hands...",
    "Vision clears...",
    "Standing tall once more...",
    "Strength flows back...",
    "Wiping blood away...",
    "The trembling stops...",
    "Finding your center...",
    "Pulse returning to normal...",
    "Gritting through the pain...",
    "Bruises fading...",
    "Life force surges...",
    "Dusting yourself off...",
    "Pain is temporary...",
    "Rising from the ashes...",
    "The body endures...",
    "Willpower sustains...",
    "Numbness retreats...",
    "Resolve hardens...",
    "Bones mend...",
    "Spirit unbroken...",
    "Catching a second wind...",
    "Steadier now...",
    "The fog lifts...",
    "Battle scars earned...",
    "Still standing...",
    "Warrior's resilience...",
    "Renewed vigor...",
    "Almost whole...",
    "Flesh knits together...",
    "The bleeding stops...",
    "Centering your thoughts...",
    "Worn but unbroken...",
    "Binding the wounds...",
    "Energy trickles back...",
    "Inhale... exhale...",
    "The shaking subsides...",
    "Licking your wounds...",
    "Tested but not beaten...",
    "Patching yourself up...",
    "The fire within reignites...",
    "Composure returns...",
    "Riding out the pain...",
    "Jaw unclenches...",
    "Color returns to your face...",
    "Summoning reserves...",
    "One breath at a time...",
    "The haze clears...",
    "Tough as iron...",
    "Refusing to fall...",
    "Knees steady...",
    "A flicker of strength...",
    "Endurance prevails...",
    "Sweat cools on your brow...",
    "Reclaiming your footing...",
    "The storm inside calms...",
    "Hardened by battle...",
    "Sinew and will...",
    "Piecing yourself together...",
    "Defiant against pain...",
    "The tide turns inward...",
    "Scar tissue thickens...",
    "Unyielding spirit...",
    "Anchored in resolve...",
    "Warmth spreads through you...",
    "Battered but breathing...",
    "Survival instinct kicks in...",
    "Fueled by determination...",
    "Ready for more...",
];

/// Returns a regenerating message based on a seed value.
pub fn regen_message(seed: u64) -> &'static str {
    REGEN_MESSAGES[(seed.wrapping_mul(7) as usize) % REGEN_MESSAGES.len()]
}
